packages:
  - packages/*
  - apps/*

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  lucide-react: ^0.561.0

onlyBuiltDependencies:
  - cypress
  - esbuild
  - unrs-resolver

sideEffectsCache: false
