/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ArticlePostRequestTagsInner
 */
export interface ArticlePostRequestTagsInner {
  /**
   *
   * @type {string}
   * @memberof ArticlePostRequestTagsInner
   */
  id: string;
}

/**
 * Check if a given object implements the ArticlePostRequestTagsInner interface.
 */
export function instanceOfArticlePostRequestTagsInner(
  value: object,
): value is ArticlePostRequestTagsInner {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function ArticlePostRequestTagsInnerFromJSON(
  json: any,
): ArticlePostRequestTagsInner {
  return ArticlePostRequestTagsInnerFromJSONTyped(json, false);
}

export function ArticlePostRequestTagsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlePostRequestTagsInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function ArticlePostRequestTagsInnerToJSON(
  json: any,
): ArticlePostRequestTagsInner {
  return ArticlePostRequestTagsInnerToJSONTyped(json, false);
}

export function ArticlePostRequestTagsInnerToJSONTyped(
  value?: ArticlePostRequestTagsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
