/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticlePostRequestTagsInner } from './ArticlePostRequestTagsInner';
import {
  ArticlePostRequestTagsInnerFromJSON,
  ArticlePostRequestTagsInnerFromJSONTyped,
  ArticlePostRequestTagsInnerToJSON,
  ArticlePostRequestTagsInnerToJSONTyped,
} from './ArticlePostRequestTagsInner';

/**
 *
 * @export
 * @interface ArticlePostRequest
 */
export interface ArticlePostRequest {
  /**
   *
   * @type {string}
   * @memberof ArticlePostRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ArticlePostRequest
   */
  content: string;
  /**
   *
   * @type {Array<ArticlePostRequestTagsInner>}
   * @memberof ArticlePostRequest
   */
  tags: Array<ArticlePostRequestTagsInner>;
}

/**
 * Check if a given object implements the ArticlePostRequest interface.
 */
export function instanceOfArticlePostRequest(
  value: object,
): value is ArticlePostRequest {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('tags' in value) || value['tags'] === undefined) return false;
  return true;
}

export function ArticlePostRequestFromJSON(json: any): ArticlePostRequest {
  return ArticlePostRequestFromJSONTyped(json, false);
}

export function ArticlePostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlePostRequest {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    content: json['content'],
    tags: (json['tags'] as Array<any>).map(ArticlePostRequestTagsInnerFromJSON),
  };
}

export function ArticlePostRequestToJSON(json: any): ArticlePostRequest {
  return ArticlePostRequestToJSONTyped(json, false);
}

export function ArticlePostRequestToJSONTyped(
  value?: ArticlePostRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    content: value['content'],
    tags: (value['tags'] as Array<any>).map(ArticlePostRequestTagsInnerToJSON),
  };
}
