/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
  TagFromJSON,
  TagFromJSONTyped,
  TagToJSON,
  TagToJSONTyped,
} from './Tag';

/**
 *
 * @export
 * @interface Article
 */
export interface Article {
  /**
   *
   * @type {string}
   * @memberof Article
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Article
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Article
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof Article
   */
  userEmail: string;
  /**
   *
   * @type {string}
   * @memberof Article
   */
  userID: string;
  /**
   *
   * @type {Array<Tag>}
   * @memberof Article
   */
  tags: Array<Tag>;
  /**
   *
   * @type {string}
   * @memberof Article
   */
  createTime: string;
  /**
   *
   * @type {string}
   * @memberof Article
   */
  updateTime: string;
  /**
   *
   * @type {boolean}
   * @memberof Article
   */
  isDeleted: boolean;
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): value is Article {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('userEmail' in value) || value['userEmail'] === undefined) return false;
  if (!('userID' in value) || value['userID'] === undefined) return false;
  if (!('tags' in value) || value['tags'] === undefined) return false;
  if (!('createTime' in value) || value['createTime'] === undefined)
    return false;
  if (!('updateTime' in value) || value['updateTime'] === undefined)
    return false;
  if (!('isDeleted' in value) || value['isDeleted'] === undefined) return false;
  return true;
}

export function ArticleFromJSON(json: any): Article {
  return ArticleFromJSONTyped(json, false);
}

export function ArticleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Article {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    content: json['content'],
    userEmail: json['userEmail'],
    userID: json['userID'],
    tags: (json['tags'] as Array<any>).map(TagFromJSON),
    createTime: json['createTime'],
    updateTime: json['updateTime'],
    isDeleted: json['isDeleted'],
  };
}

export function ArticleToJSON(json: any): Article {
  return ArticleToJSONTyped(json, false);
}

export function ArticleToJSONTyped(
  value?: Article | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    title: value['title'],
    content: value['content'],
    userEmail: value['userEmail'],
    userID: value['userID'],
    tags: (value['tags'] as Array<any>).map(TagToJSON),
    createTime: value['createTime'],
    updateTime: value['updateTime'],
    isDeleted: value['isDeleted'],
  };
}
