/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Article } from './Article';
import {
  ArticleFromJSON,
  ArticleFromJSONTyped,
  ArticleToJSON,
  ArticleToJSONTyped,
} from './Article';

/**
 *
 * @export
 * @interface ArticlesGet200Response
 */
export interface ArticlesGet200Response {
  /**
   *
   * @type {string}
   * @memberof ArticlesGet200Response
   */
  nextID: string;
  /**
   *
   * @type {Array<Article>}
   * @memberof ArticlesGet200Response
   */
  articles: Array<Article>;
}

/**
 * Check if a given object implements the ArticlesGet200Response interface.
 */
export function instanceOfArticlesGet200Response(
  value: object,
): value is ArticlesGet200Response {
  if (!('nextID' in value) || value['nextID'] === undefined) return false;
  if (!('articles' in value) || value['articles'] === undefined) return false;
  return true;
}

export function ArticlesGet200ResponseFromJSON(
  json: any,
): ArticlesGet200Response {
  return ArticlesGet200ResponseFromJSONTyped(json, false);
}

export function ArticlesGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesGet200Response {
  if (json == null) {
    return json;
  }
  return {
    nextID: json['nextID'],
    articles: (json['articles'] as Array<any>).map(ArticleFromJSON),
  };
}

export function ArticlesGet200ResponseToJSON(
  json: any,
): ArticlesGet200Response {
  return ArticlesGet200ResponseToJSONTyped(json, false);
}

export function ArticlesGet200ResponseToJSONTyped(
  value?: ArticlesGet200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    nextID: value['nextID'],
    articles: (value['articles'] as Array<any>).map(ArticleToJSON),
  };
}
