/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Author
 */
export interface Author {
  /**
   *
   * @type {string}
   * @memberof Author
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof Author
   */
  userID: string;
}

/**
 * Check if a given object implements the Author interface.
 */
export function instanceOfAuthor(value: object): value is Author {
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('userID' in value) || value['userID'] === undefined) return false;
  return true;
}

export function AuthorFromJSON(json: any): Author {
  return AuthorFromJSONTyped(json, false);
}

export function AuthorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Author {
  if (json == null) {
    return json;
  }
  return {
    username: json['username'],
    userID: json['userID'],
  };
}

export function AuthorToJSON(json: any): Author {
  return AuthorToJSONTyped(json, false);
}

export function AuthorToJSONTyped(
  value?: Author | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    username: value['username'],
    userID: value['userID'],
  };
}
