/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TagIdDelete200Response
 */
export interface TagIdDelete200Response {
  /**
   *
   * @type {string}
   * @memberof TagIdDelete200Response
   */
  message: string;
}

/**
 * Check if a given object implements the TagIdDelete200Response interface.
 */
export function instanceOfTagIdDelete200Response(
  value: object,
): value is TagIdDelete200Response {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function TagIdDelete200ResponseFromJSON(
  json: any,
): TagIdDelete200Response {
  return TagIdDelete200ResponseFromJSONTyped(json, false);
}

export function TagIdDelete200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagIdDelete200Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function TagIdDelete200ResponseToJSON(
  json: any,
): TagIdDelete200Response {
  return TagIdDelete200ResponseToJSONTyped(json, false);
}

export function TagIdDelete200ResponseToJSONTyped(
  value?: TagIdDelete200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
