/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TagPostRequest
 */
export interface TagPostRequest {
  /**
   *
   * @type {string}
   * @memberof TagPostRequest
   */
  name: string;
}

/**
 * Check if a given object implements the TagPostRequest interface.
 */
export function instanceOfTagPostRequest(
  value: object,
): value is TagPostRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function TagPostRequestFromJSON(json: any): TagPostRequest {
  return TagPostRequestFromJSONTyped(json, false);
}

export function TagPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagPostRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function TagPostRequestToJSON(json: any): TagPostRequest {
  return TagPostRequestToJSONTyped(json, false);
}

export function TagPostRequestToJSONTyped(
  value?: TagPostRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
