/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TagPost401Response
 */
export interface TagPost401Response {
  /**
   *
   * @type {string}
   * @memberof TagPost401Response
   */
  message: string;
}

/**
 * Check if a given object implements the TagPost401Response interface.
 */
export function instanceOfTagPost401Response(
  value: object,
): value is TagPost401Response {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function TagPost401ResponseFromJSON(json: any): TagPost401Response {
  return TagPost401ResponseFromJSONTyped(json, false);
}

export function TagPost401ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagPost401Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function TagPost401ResponseToJSON(json: any): TagPost401Response {
  return TagPost401ResponseToJSONTyped(json, false);
}

export function TagPost401ResponseToJSONTyped(
  value?: TagPost401Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
