/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TagPost400Response
 */
export interface TagPost400Response {
  /**
   *
   * @type {string}
   * @memberof TagPost400Response
   */
  message: string;
}

/**
 * Check if a given object implements the TagPost400Response interface.
 */
export function instanceOfTagPost400Response(
  value: object,
): value is TagPost400Response {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function TagPost400ResponseFromJSON(json: any): TagPost400Response {
  return TagPost400ResponseFromJSONTyped(json, false);
}

export function TagPost400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagPost400Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function TagPost400ResponseToJSON(json: any): TagPost400Response {
  return TagPost400ResponseToJSONTyped(json, false);
}

export function TagPost400ResponseToJSONTyped(
  value?: TagPost400Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
