/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
  TagFromJSON,
  TagFromJSONTyped,
  TagToJSON,
  TagToJSONTyped,
} from './Tag';

/**
 *
 * @export
 * @interface TagsGet200Response
 */
export interface TagsGet200Response {
  /**
   *
   * @type {Array<Tag>}
   * @memberof TagsGet200Response
   */
  tags: Array<Tag>;
  /**
   *
   * @type {string}
   * @memberof TagsGet200Response
   */
  lastID: string;
  /**
   *
   * @type {boolean}
   * @memberof TagsGet200Response
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the TagsGet200Response interface.
 */
export function instanceOfTagsGet200Response(
  value: object,
): value is TagsGet200Response {
  if (!('tags' in value) || value['tags'] === undefined) return false;
  if (!('lastID' in value) || value['lastID'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function TagsGet200ResponseFromJSON(json: any): TagsGet200Response {
  return TagsGet200ResponseFromJSONTyped(json, false);
}

export function TagsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TagsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    tags: (json['tags'] as Array<any>).map(TagFromJSON),
    lastID: json['lastID'],
    hasMore: json['hasMore'],
  };
}

export function TagsGet200ResponseToJSON(json: any): TagsGet200Response {
  return TagsGet200ResponseToJSONTyped(json, false);
}

export function TagsGet200ResponseToJSONTyped(
  value?: TagsGet200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    tags: (value['tags'] as Array<any>).map(TagToJSON),
    lastID: value['lastID'],
    hasMore: value['hasMore'],
  };
}
