/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  Article,
  ArticlePostRequest,
  Tag,
  TagIdDelete200Response,
  TagPost400Response,
  TagPost401Response,
} from '../models/index';
import {
  ArticleFromJSON,
  ArticleToJSON,
  ArticlePostRequestFromJSON,
  ArticlePostRequestToJSON,
  TagFromJSON,
  TagToJSON,
  TagIdDelete200ResponseFromJSON,
  TagIdDelete200ResponseToJSON,
  TagPost400ResponseFromJSON,
  TagPost400ResponseToJSON,
  TagPost401ResponseFromJSON,
  TagPost401ResponseToJSON,
} from '../models/index';

export interface ArticleIdDeleteRequest {
  id: string;
}

export interface ArticleIdPutRequest {
  id: string;
  articlePostRequest: ArticlePostRequest;
}

export interface ArticlePostOperationRequest {
  articlePostRequest: ArticlePostRequest;
}

export interface TagIdDeleteRequest {
  id: string;
}

export interface TagIdPutRequest {
  id: string;
  name?: string;
}

export interface TagPostRequest {
  name?: string;
}

/**
 * AuthedApi - interface
 *
 * @export
 * @interface AuthedApiInterface
 */
export interface AuthedApiInterface {
  /**
   *
   * @summary Delete an article
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthedApiInterface
   */
  articleIdDeleteRaw(
    requestParameters: ArticleIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TagIdDelete200Response>>;

  /**
   *
   * Delete an article
   */
  articleIdDelete(
    requestParameters: ArticleIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TagIdDelete200Response>;

  /**
   *
   * @summary Update an article
   * @param {string} id
   * @param {ArticlePostRequest} articlePostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthedApiInterface
   */
  articleIdPutRaw(
    requestParameters: ArticleIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>>;

  /**
   *
   * Update an article
   */
  articleIdPut(
    requestParameters: ArticleIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article>;

  /**
   *
   * @summary Create an article
   * @param {ArticlePostRequest} articlePostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthedApiInterface
   */
  articlePostRaw(
    requestParameters: ArticlePostOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>>;

  /**
   *
   * Create an article
   */
  articlePost(
    requestParameters: ArticlePostOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article>;

  /**
   *
   * @summary Delete a tag
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthedApiInterface
   */
  tagIdDeleteRaw(
    requestParameters: TagIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TagIdDelete200Response>>;

  /**
   *
   * Delete a tag
   */
  tagIdDelete(
    requestParameters: TagIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TagIdDelete200Response>;

  /**
   *
   * @summary Update a tag
   * @param {string} id
   * @param {string} [name]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthedApiInterface
   */
  tagIdPutRaw(
    requestParameters: TagIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>>;

  /**
   *
   * Update a tag
   */
  tagIdPut(
    requestParameters: TagIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag>;

  /**
   *
   * @summary Create a tag
   * @param {string} [name]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthedApiInterface
   */
  tagPostRaw(
    requestParameters: TagPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>>;

  /**
   *
   * Create a tag
   */
  tagPost(
    requestParameters: TagPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag>;
}

/**
 *
 */
export class AuthedApi extends runtime.BaseAPI implements AuthedApiInterface {
  /**
   *
   * Delete an article
   */
  async articleIdDeleteRaw(
    requestParameters: ArticleIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TagIdDelete200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling articleIdDelete().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/article/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TagIdDelete200ResponseFromJSON(jsonValue),
    );
  }

  /**
   *
   * Delete an article
   */
  async articleIdDelete(
    requestParameters: ArticleIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TagIdDelete200Response> {
    const response = await this.articleIdDeleteRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   *
   * Update an article
   */
  async articleIdPutRaw(
    requestParameters: ArticleIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling articleIdPut().',
      );
    }

    if (requestParameters['articlePostRequest'] == null) {
      throw new runtime.RequiredError(
        'articlePostRequest',
        'Required parameter "articlePostRequest" was null or undefined when calling articleIdPut().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/article/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: ArticlePostRequestToJSON(requestParameters['articlePostRequest']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ArticleFromJSON(jsonValue),
    );
  }

  /**
   *
   * Update an article
   */
  async articleIdPut(
    requestParameters: ArticleIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article> {
    const response = await this.articleIdPutRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   *
   * Create an article
   */
  async articlePostRaw(
    requestParameters: ArticlePostOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>> {
    if (requestParameters['articlePostRequest'] == null) {
      throw new runtime.RequiredError(
        'articlePostRequest',
        'Required parameter "articlePostRequest" was null or undefined when calling articlePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/article`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ArticlePostRequestToJSON(requestParameters['articlePostRequest']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ArticleFromJSON(jsonValue),
    );
  }

  /**
   *
   * Create an article
   */
  async articlePost(
    requestParameters: ArticlePostOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article> {
    const response = await this.articlePostRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   *
   * Delete a tag
   */
  async tagIdDeleteRaw(
    requestParameters: TagIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TagIdDelete200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling tagIdDelete().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tag/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TagIdDelete200ResponseFromJSON(jsonValue),
    );
  }

  /**
   *
   * Delete a tag
   */
  async tagIdDelete(
    requestParameters: TagIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TagIdDelete200Response> {
    const response = await this.tagIdDeleteRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   *
   * Update a tag
   */
  async tagIdPutRaw(
    requestParameters: TagIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling tagIdPut().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['name'] != null) {
      queryParameters['name'] = requestParameters['name'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tag/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TagFromJSON(jsonValue),
    );
  }

  /**
   *
   * Update a tag
   */
  async tagIdPut(
    requestParameters: TagIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag> {
    const response = await this.tagIdPutRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   *
   * Create a tag
   */
  async tagPostRaw(
    requestParameters: TagPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>> {
    const queryParameters: any = {};

    if (requestParameters['name'] != null) {
      queryParameters['name'] = requestParameters['name'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tag`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TagFromJSON(jsonValue),
    );
  }

  /**
   *
   * Create a tag
   */
  async tagPost(
    requestParameters: TagPostRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag> {
    const response = await this.tagPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
