/* tslint:disable */
/* eslint-disable */
/**
 * Article Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  Article,
  ArticlesGet200Response,
  TagPost400Response,
  TagPost401Response,
  TagsGet200Response,
} from '../models/index';
import {
  ArticleFromJSON,
  ArticleToJSON,
  ArticlesGet200ResponseFromJSON,
  ArticlesGet200ResponseToJSON,
  TagPost400ResponseFromJSON,
  TagPost400ResponseToJSON,
  TagPost401ResponseFromJSON,
  TagPost401ResponseToJSON,
  TagsGet200ResponseFromJSON,
  TagsGet200ResponseToJSON,
} from '../models/index';

export interface ArticleIdGetRequest {
  id: string;
}

export interface ArticlesGetRequest {
  lastID?: string;
  limit?: number;
  author?: string;
}

export interface TagsGetRequest {
  lastID?: string;
  limit?: number;
  name?: string;
}

/**
 * DefaultApi - interface
 *
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
  /**
   *
   * @summary Get a article
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  articleIdGetRaw(
    requestParameters: ArticleIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>>;

  /**
   *
   * Get a article
   */
  articleIdGet(
    requestParameters: ArticleIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article>;

  /**
   *
   * @summary Get article list
   * @param {string} [lastID]
   * @param {number} [limit]
   * @param {string} [author] filter by author name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  articlesGetRaw(
    requestParameters: ArticlesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ArticlesGet200Response>>;

  /**
   *
   * Get article list
   */
  articlesGet(
    requestParameters: ArticlesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ArticlesGet200Response>;

  /**
   *
   * @summary Get tag list
   * @param {string} [lastID]
   * @param {number} [limit]
   * @param {string} [name] filter by tag name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  tagsGetRaw(
    requestParameters: TagsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TagsGet200Response>>;

  /**
   *
   * Get tag list
   */
  tagsGet(
    requestParameters: TagsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TagsGet200Response>;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {
  /**
   *
   * Get a article
   */
  async articleIdGetRaw(
    requestParameters: ArticleIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling articleIdGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/article/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ArticleFromJSON(jsonValue),
    );
  }

  /**
   *
   * Get a article
   */
  async articleIdGet(
    requestParameters: ArticleIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article> {
    const response = await this.articleIdGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   *
   * Get article list
   */
  async articlesGetRaw(
    requestParameters: ArticlesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ArticlesGet200Response>> {
    const queryParameters: any = {};

    if (requestParameters['lastID'] != null) {
      queryParameters['lastID'] = requestParameters['lastID'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['author'] != null) {
      queryParameters['author'] = requestParameters['author'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/articles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ArticlesGet200ResponseFromJSON(jsonValue),
    );
  }

  /**
   *
   * Get article list
   */
  async articlesGet(
    requestParameters: ArticlesGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ArticlesGet200Response> {
    const response = await this.articlesGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   *
   * Get tag list
   */
  async tagsGetRaw(
    requestParameters: TagsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TagsGet200Response>> {
    const queryParameters: any = {};

    if (requestParameters['lastID'] != null) {
      queryParameters['lastID'] = requestParameters['lastID'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['name'] != null) {
      queryParameters['name'] = requestParameters['name'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tags`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TagsGet200ResponseFromJSON(jsonValue),
    );
  }

  /**
   *
   * Get tag list
   */
  async tagsGet(
    requestParameters: TagsGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TagsGet200Response> {
    const response = await this.tagsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
