/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LogoutRouteImport } from './routes/logout';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthedRouteImport } from './routes/_authed';
import { Route as AuthedIndexRouteImport } from './routes/_authed.index';
import { Route as ApiTagsRouteImport } from './routes/api/tags';
import { Route as ApiArticlesRouteImport } from './routes/api/articles';
import { Route as AuthedEditRouteImport } from './routes/_authed.edit';
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs';
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request';
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names';
import { Route as ApiTagChar123TagIDChar125RouteImport } from './routes/api/tag.{-$tagID}';
import { Route as ApiArticleArticleIDRouteImport } from './routes/api/article.$articleID';
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index';
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode';
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr';
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only';

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any);
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiArticlesRoute = ApiArticlesRouteImport.update({
  id: '/api/articles',
  path: '/api/articles',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedEditRoute = AuthedEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedRoute,
} as any);
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any);
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any);
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTagChar123TagIDChar125Route =
  ApiTagChar123TagIDChar125RouteImport.update({
    id: '/api/tag/{-$tagID}',
    path: '/api/tag/{-$tagID}',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiArticleArticleIDRoute = ApiArticleArticleIDRouteImport.update({
  id: '/api/article/$articleID',
  path: '/api/article/$articleID',
  getParentRoute: () => rootRouteImport,
} as any);
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any);
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any);
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any);
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute;
  '/logout': typeof LogoutRoute;
  '/edit': typeof AuthedEditRoute;
  '/api/articles': typeof ApiArticlesRoute;
  '/api/tags': typeof ApiTagsRoute;
  '/': typeof AuthedIndexRoute;
  '/api/article/$articleID': typeof ApiArticleArticleIDRoute;
  '/api/tag/{-$tagID}': typeof ApiTagChar123TagIDChar125Route;
  '/demo/api/names': typeof DemoApiNamesRoute;
  '/demo/start/api-request': typeof DemoStartApiRequestRoute;
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute;
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute;
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute;
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute;
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/logout': typeof LogoutRoute;
  '/edit': typeof AuthedEditRoute;
  '/api/articles': typeof ApiArticlesRoute;
  '/api/tags': typeof ApiTagsRoute;
  '/': typeof AuthedIndexRoute;
  '/api/article/$articleID': typeof ApiArticleArticleIDRoute;
  '/api/tag/{-$tagID}': typeof ApiTagChar123TagIDChar125Route;
  '/demo/api/names': typeof DemoApiNamesRoute;
  '/demo/start/api-request': typeof DemoStartApiRequestRoute;
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute;
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute;
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute;
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute;
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authed': typeof AuthedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/logout': typeof LogoutRoute;
  '/_authed/edit': typeof AuthedEditRoute;
  '/api/articles': typeof ApiArticlesRoute;
  '/api/tags': typeof ApiTagsRoute;
  '/_authed/': typeof AuthedIndexRoute;
  '/api/article/$articleID': typeof ApiArticleArticleIDRoute;
  '/api/tag/{-$tagID}': typeof ApiTagChar123TagIDChar125Route;
  '/demo/api/names': typeof DemoApiNamesRoute;
  '/demo/start/api-request': typeof DemoStartApiRequestRoute;
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute;
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute;
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute;
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute;
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/login'
    | '/logout'
    | '/edit'
    | '/api/articles'
    | '/api/tags'
    | '/'
    | '/api/article/$articleID'
    | '/api/tag/{-$tagID}'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/logout'
    | '/edit'
    | '/api/articles'
    | '/api/tags'
    | '/'
    | '/api/article/$articleID'
    | '/api/tag/{-$tagID}'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr';
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/_authed/edit'
    | '/api/articles'
    | '/api/tags'
    | '/_authed/'
    | '/api/article/$articleID'
    | '/api/tag/{-$tagID}'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  LogoutRoute: typeof LogoutRoute;
  ApiArticlesRoute: typeof ApiArticlesRoute;
  ApiTagsRoute: typeof ApiTagsRoute;
  ApiArticleArticleIDRoute: typeof ApiArticleArticleIDRoute;
  ApiTagChar123TagIDChar125Route: typeof ApiTagChar123TagIDChar125Route;
  DemoApiNamesRoute: typeof DemoApiNamesRoute;
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute;
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute;
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute;
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute;
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute;
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout';
      path: '/logout';
      fullPath: '/logout';
      preLoaderRoute: typeof LogoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed': {
      id: '/_authed';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed/': {
      id: '/_authed/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthedIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/api/tags': {
      id: '/api/tags';
      path: '/api/tags';
      fullPath: '/api/tags';
      preLoaderRoute: typeof ApiTagsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/articles': {
      id: '/api/articles';
      path: '/api/articles';
      fullPath: '/api/articles';
      preLoaderRoute: typeof ApiArticlesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed/edit': {
      id: '/_authed/edit';
      path: '/edit';
      fullPath: '/edit';
      preLoaderRoute: typeof AuthedEditRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs';
      path: '/demo/start/server-funcs';
      fullPath: '/demo/start/server-funcs';
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/demo/start/api-request': {
      id: '/demo/start/api-request';
      path: '/demo/start/api-request';
      fullPath: '/demo/start/api-request';
      preLoaderRoute: typeof DemoStartApiRequestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/demo/api/names': {
      id: '/demo/api/names';
      path: '/demo/api/names';
      fullPath: '/demo/api/names';
      preLoaderRoute: typeof DemoApiNamesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/tag/{-$tagID}': {
      id: '/api/tag/{-$tagID}';
      path: '/api/tag/{-$tagID}';
      fullPath: '/api/tag/{-$tagID}';
      preLoaderRoute: typeof ApiTagChar123TagIDChar125RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/article/$articleID': {
      id: '/api/article/$articleID';
      path: '/api/article/$articleID';
      fullPath: '/api/article/$articleID';
      preLoaderRoute: typeof ApiArticleArticleIDRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/';
      path: '/demo/start/ssr';
      fullPath: '/demo/start/ssr';
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode';
      path: '/demo/start/ssr/spa-mode';
      fullPath: '/demo/start/ssr/spa-mode';
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr';
      path: '/demo/start/ssr/full-ssr';
      fullPath: '/demo/start/ssr/full-ssr';
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only';
      path: '/demo/start/ssr/data-only';
      fullPath: '/demo/start/ssr/data-only';
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthedRouteChildren {
  AuthedEditRoute: typeof AuthedEditRoute;
  AuthedIndexRoute: typeof AuthedIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedEditRoute: AuthedEditRoute,
  AuthedIndexRoute: AuthedIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiArticlesRoute: ApiArticlesRoute,
  ApiTagsRoute: ApiTagsRoute,
  ApiArticleArticleIDRoute: ApiArticleArticleIDRoute,
  ApiTagChar123TagIDChar125Route: ApiTagChar123TagIDChar125Route,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
