import tailwindcss from '@tailwindcss/vite';
import { devtools } from '@tanstack/devtools-vite';
import { tanstackStart } from '@tanstack/react-start/plugin/vite';
import viteReact from '@vitejs/plugin-react';
import { nitro } from 'nitro/vite';
import path from 'node:path';
import { defineConfig } from 'vite';
import viteTsConfigPaths from 'vite-tsconfig-paths';

const config = defineConfig({
  resolve: {
    // Cannot disable the main field in api generated by openapi-generator, so have to hardcode the order here
    mainFields: ['module', 'jsnext:main', 'jsnext', 'main'],
    alias: {
      '@workspace/ui': path.resolve(__dirname, '../../packages/ui/src'),
    },
  },
  plugins: [
    devtools({
      eventBusConfig: {
        port: 42070,
      },
    }),
    nitro(),
    viteTsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
    tailwindcss(),
    tanstackStart(),
    viteReact(),
  ],
});

export default config;
